CREATE TABLE dbo.admins
(
    Id NVARCHAR(45) NOT NULL IDENTITY (1,1),
    name NVARCHAR(30),
    password NVARCHAR(40) UNIQUE NOT NULL,
    email NVARCHAR(20) UNIQUE NOT NULL,
    role NVARCHAR(10) NOT NULL,
    createdAt DATETIME2 DEFAULT GETDATE(),
    PRIMARY KEY(Id)
)