CREATE TABLE Admin
(
    Id NVARCHAR(45) NOT NULL,
    name NVARCHAR(30),
    password NVARCHAR(200) UNIQUE NOT NULL,
    email NVARCHAR(100) UNIQUE NOT NULL,
    role NVARCHAR(10) NOT NULL,
    createdAt DATETIME2 DEFAULT GETDATE(),
    PRIMARY KEY(Id)
)